// utils/exportPdf.ts
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system";
import { fetchDailySummary } from "./export";

const buildPdfHtml = (daily: Awaited<ReturnType<typeof fetchDailySummary>>) => {
  if (daily.length === 0) {
    return `
      <html>
        <body style="font-family: system-ui, -apple-system, sans-serif; padding: 24px;">
          <h1>Headfree – 30 day migraine summary</h1>
          <p>No data available for the last 30 days.</p>
        </body>
      </html>
    `;
  }

  const totalDays = daily.length;
  const migraineDays = daily.filter((d) => d.migraine_today).length;
  const avgProb =
    daily.reduce((sum, d) => sum + (d.prediction?.probability ?? 0), 0) /
    totalDays;

  const rowsHtml = daily
    .map((d) => {
      const prob = d.prediction?.probability ?? 0;
      const probPct = Math.round(prob * 100);
      const barWidth = Math.max(5, probPct); // always at least visible
      const risk = d.prediction?.risk_level ?? "n/a";

      return `
        <tr>
          <td>${d.date}</td>
          <td style="text-align:center;">${d.migraine_today ? "✔" : "✘"}</td>
          <td>${risk}</td>
          <td style="width: 35%;">
            <div style="height: 10px; background:#eee; border-radius:4px;">
              <div style="height: 10px; width:${barWidth}%; background:#4a90e2; border-radius:4px;"></div>
            </div>
            <div style="font-size:10px; text-align:right;">${probPct}%</div>
          </td>
          <td style="text-align:center;">${d.sleep.total_minutes ?? ""}</td>
          <td style="text-align:center;">${d.lifestyle.stress_level ?? ""}</td>
        </tr>
      `;
    })
    .join("");

  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <title>Headfree – 30 day summary</title>
    </head>
    <body style="font-family: system-ui, -apple-system, sans-serif; padding: 24px;">
      <h1 style="margin-top:0;">Headfree – 30 day migraine summary</h1>

      <h2>Overview</h2>
      <ul>
        <li>Days with data: <strong>${totalDays}</strong></li>
        <li>Days with migraine: <strong>${migraineDays}</strong></li>
        <li>Average forecast probability: <strong>${Math.round(
          avgProb * 100
        )}%</strong></li>
      </ul>

      <h2>Daily overview</h2>
      <p style="font-size: 12px; color:#666;">
        Simple chart: blue bar shows predicted migraine probability for each day.
      </p>

      <table style="width:100%; border-collapse:collapse; font-size:12px;">
        <thead>
          <tr>
            <th style="text-align:left; border-bottom:1px solid #ccc;">Date</th>
            <th style="border-bottom:1px solid #ccc;">Migraine</th>
            <th style="text-align:left; border-bottom:1px solid #ccc;">Forecast tier</th>
            <th style="text-align:left; border-bottom:1px solid #ccc;">Probability</th>
            <th style="border-bottom:1px solid #ccc;">Sleep (min)</th>
            <th style="border-bottom:1px solid #ccc;">Stress</th>
          </tr>
        </thead>
        <tbody>
          ${rowsHtml}
        </tbody>
      </table>

      <p style="margin-top:32px; font-size:10px; color:#666;">
        This report was generated by the Headfree prototype. Values and thresholds are for personal use and should be interpreted by a medical professional.
      </p>
    </body>
  </html>
  `;
};

export const exportSummaryPdf = async (uid: string) => {
  const daily = await fetchDailySummary(uid);
  const html = buildPdfHtml(daily);

  const { uri } = await Print.printToFileAsync({
    html,
  });

  // move it into documentDirectory with a friendly name (optional)
  const safeTs = new Date().toISOString().replace(/[:.]/g, "-");
  const pdfName = `headfree-summary-${uid}-${safeTs}.pdf`;
  const pdfUri = FileSystem.documentDirectory + pdfName;
  await FileSystem.moveAsync({ from: uri, to: pdfUri });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(pdfUri, {
      mimeType: "application/pdf",
      dialogTitle: "Headfree 30 day summary",
    });
  }

  return pdfUri;
};
